# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: twitter.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='twitter.proto',
  package='l1',
  serialized_pb='\n\rtwitter.proto\x12\x02l1\"\x8e\x01\n\x05Tweet\x12 \n\x06insert\x18\x01 \x01(\x0b\x32\x10.l1.Tweet.Insert\x1a\x63\n\x06Insert\x12\x0c\n\x04text\x18\x01 \x02(\t\x12\n\n\x02id\x18\x02 \x02(\x03\x12\x0c\n\x04u_id\x18\x03 \x02(\x03\x12\x0e\n\x06u_name\x18\x04 \x02(\t\x12\r\n\x05model\x18\x05 \x02(\t\x12\x12\n\ncreated_at\x18\x06 \x02(\t\"#\n\x06Tweets\x12\x19\n\x06tweets\x18\x01 \x03(\x0b\x32\t.l1.Tweet')




_TWEET_INSERT = _descriptor.Descriptor(
  name='Insert',
  full_name='l1.Tweet.Insert',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='l1.Tweet.Insert.text', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='id', full_name='l1.Tweet.Insert.id', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='u_id', full_name='l1.Tweet.Insert.u_id', index=2,
      number=3, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='u_name', full_name='l1.Tweet.Insert.u_name', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='model', full_name='l1.Tweet.Insert.model', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='created_at', full_name='l1.Tweet.Insert.created_at', index=5,
      number=6, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=65,
  serialized_end=164,
)

_TWEET = _descriptor.Descriptor(
  name='Tweet',
  full_name='l1.Tweet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='insert', full_name='l1.Tweet.insert', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_TWEET_INSERT, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=22,
  serialized_end=164,
)


_TWEETS = _descriptor.Descriptor(
  name='Tweets',
  full_name='l1.Tweets',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tweets', full_name='l1.Tweets.tweets', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=166,
  serialized_end=201,
)

_TWEET_INSERT.containing_type = _TWEET;
_TWEET.fields_by_name['insert'].message_type = _TWEET_INSERT
_TWEETS.fields_by_name['tweets'].message_type = _TWEET
DESCRIPTOR.message_types_by_name['Tweet'] = _TWEET
DESCRIPTOR.message_types_by_name['Tweets'] = _TWEETS

class Tweet(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType

  class Insert(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _TWEET_INSERT

    # @@protoc_insertion_point(class_scope:l1.Tweet.Insert)
  DESCRIPTOR = _TWEET

  # @@protoc_insertion_point(class_scope:l1.Tweet)

class Tweets(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TWEETS

  # @@protoc_insertion_point(class_scope:l1.Tweets)


# @@protoc_insertion_point(module_scope)
